In [1]:
import tensorflow as tf
help(tf.concat)

Help on function concat in module tensorflow.python.ops.array_ops:

concat(values, axis, name='concat')
    Concatenates tensors along one dimension.
    
    Concatenates the list of tensors `values` along dimension `axis`.  If
    `values[i].shape = [D0, D1, ... Daxis(i), ...Dn]`, the concatenated
    result has shape
    
        [D0, D1, ... Raxis, ...Dn]
    
    where
    
        Raxis = sum(Daxis(i))
    
    That is, the data from the input tensors is joined along the `axis`
    dimension.
    
    The number of dimensions of the input tensors must match, and all dimensions
    except `axis` must be equal.
    
    For example:
    
    >>> t1 = [[1, 2, 3], [4, 5, 6]]
    >>> t2 = [[7, 8, 9], [10, 11, 12]]
    >>> concat([t1, t2], 0)
    <tf.Tensor: shape=(4, 3), dtype=int32, numpy=
    array([[ 1,  2,  3],
           [ 4,  5,  6],
           [ 7,  8,  9],
           [10, 11, 12]], dtype=int32)>
    
    >>> concat([t1, t2], 1)
    <tf.Tensor: shape=(2, 6), dtype=int32, numpy=

In [2]:
a = tf.cast([[1, 2]], dtype=tf.float16)

In [4]:
a.shape[1]

2